import { Priority, Difficulty, Status, TableData } from "@/features/ehafal/types";

export const mockData: TableData[] = [
    {
        id: 'MEM-001',
        target: 'Surah Al-Fatiha',
        scope: 'Verse 1-7',
        status: Status.IN_PROGRESS,
        progress: '75%',
        startTime: '2024-03-15 08:00',
        duration: '3d 5h',
        difficulty: Difficulty.MEDIUM,
        priority: Priority.HIGH,
    },
    {
        id: 'MEM-002',
        target: 'Surah Al-Ikhlas',
        scope: 'Full',
        status: Status.COMPLETED,
        progress: '100%',
        startTime: '2024-03-10 14:30',
        duration: '8d 2h',
        difficulty: Difficulty.EASY,
        priority: Priority.MEDIUM,
    },
    {
        id: 'MEM-003',
        target: 'Surah Al-Falaq',
        scope: 'Verse 1-3',
        status: Status.PENDING,
        progress: '0%',
        startTime: '2024-03-18 10:00',
        duration: '5h',
        difficulty: Difficulty.HARD,
        priority: Priority.HIGH,
    },
    {
        id: 'MEM-004',
        target: 'Surah Al-Kahfi',
        scope: 'Verse 1-3',
        status: Status.PENDING,
        progress: '45%',
        startTime: '2024-03-18 10:00',
        duration: '5h',
        difficulty: Difficulty.HARD,
        priority: Priority.HIGH,
    },
    {
        id: 'MEM-005',
        target: 'Surah Al-Kahfi',
        scope: 'Verse 1-10',
        status: Status.PENDING,
        progress: '2.5%',
        startTime: '2024-03-18 10:00',
        duration: '5h',
        difficulty: Difficulty.HARD,
        priority: Priority.HIGH,
    }
];