import { Priority, Difficulty, Status, TableData } from "@/features/ehafal/types";

export const mockData: TableData[] = [
    {
        id: 'MEM-001',
        target: 'Surah Al-Fatiha Ayat 1-7',
        scope: 'Al-Quran',
        status: Status.IN_PROGRESS,
        progress: '75%',
        startTime: '2024-03-15 08:00',
        duration: '3d 5h',
        difficulty: Difficulty.MEDIUM,
        priority: Priority.HIGH,
    },
    {
        id: 'MEM-002',
        target: 'Surah Al-Ikhlas Ayat 1-3',
        scope: 'Al-Quran',
        status: Status.COMPLETED,
        progress: '100%',
        startTime: '2024-03-10 14:30',
        duration: '8d 2h',
        difficulty: Difficulty.EASY,
        priority: Priority.MEDIUM,
    },
    {
        id: 'MEM-003',
        target: 'Surah Al-Falaq Ayat 1-3',
        scope: 'Al-Quran',
        status: Status.PENDING,
        progress: '0%',
        startTime: '2024-03-18 10:00',
        duration: '5h',
        difficulty: Difficulty.HARD,
        priority: Priority.HIGH,
    },
    {
        id: 'MEM-004',
        target: 'Surah Al-Kahfi Ayat 1-3',
        scope: 'Al-Quran',
        status: Status.PENDING,
        progress: '45%',
        startTime: '2024-03-18 10:00',
        duration: '5h',
        difficulty: Difficulty.HARD,
        priority: Priority.HIGH,
    },
    {
        id: 'MEM-005',
        target: 'Surah Al-Kahfi Ayat 1-10',
        scope: 'Al-Quran',
        status: Status.PENDING,
        progress: '2.5%',
        startTime: '2024-03-18 10:00',
        duration: '5h',
        difficulty: Difficulty.HARD,
        priority: Priority.HIGH,
    },
    {
        id: 'MEM-006',
        target: 'CKA Certification How to upscale replica using kubectl',
        scope: 'Kubernetes',
        status: Status.PENDING,
        progress: '20.5%',
        startTime: '2024-03-18 10:00',
        duration: '3h',
        difficulty: Difficulty.EASY,
        priority: Priority.MEDIUM,
    },
    {
        id: 'MEM-007',
        target: 'AWS SysOps Certification ECS Fargate definition',
        scope: 'AWS',
        status: Status.PENDING,
        progress: '10.5%',
        startTime: '2024-03-18 10:00',
        duration: '3h',
        difficulty: Difficulty.EASY,
        priority: Priority.MEDIUM,
    }
];